name: Create, publish and deploy a Docker image

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/al-kot/mlse:latest
      
      - name: Deploy to vm
        env:
          VM_PASS: ${{ secrets.VM_PASS }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
        run: |
          sshpass -p $VM_PASS ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST <<EOF
          docker logout ghcr.io
          docker pull ghcr.io/al-kot/mlse:latest
          if [ ! "$(docker ps -a | grep "ak_mlse")" ]; then
            docker run -d -p 6942:6942 --name "ak_mlse" "ghcr.io/al-kot/mlse"
          else
            docker restart "ak_mlse"
          fi
          EOF
      
